import {StyleSheet} from 'react-native';
import colors from '../../assets/Colors/colors';
export const styles = StyleSheet.create({
  wrapper: {},
  slide1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.FrameColor,
  },
  slide2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.FrameColor,
  },
  headertext: {
    color: colors.Black,
    fontSize: 28,
    fontWeight: '700',
    bottom: 30,
  },
  subtitletext: {
    color: colors.Gray,
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 30,
    bottom: 20,
    textAlign: 'center',
  },
  subtitle2text: {
    color: colors.Gray,
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 20,
    bottom: 20,
    textAlign: 'center',
  },
  nextbuttonview: {
    backgroundColor: colors.PurplePrimary,
    paddingHorizontal: 120,
    paddingVertical: 15,
    position: 'absolute',
    right: 45,
    alignSelf: 'center',
    borderRadius: 14,
    marginVertical: 250,
  },
  nextbuttontext: {
    color: colors.white,
    fontSize: 18,
    fontFamily: '700',
  },
  prevbuttonView: {
    backgroundColor: colors.PurplePrimary,
    paddingHorizontal: 120,
    paddingVertical: 15,
    position: 'absolute',
    left: 20,
    alignSelf: 'center',
    borderRadius: 14,
    marginVertical: 250,
  },
  dot: {
    backgroundColor: colors.paginationcolor,
    width: 20,
    height: 5,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  activeDot: {
    backgroundColor: colors.PurplePrimary,
    width: 20,
    height: 5,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  paginationStyle: {
    position: 'absolute',
    top: -650,
  },
  image: {
    width: '65%',
    height: '35%',
    bottom: 80,
  },
});
